import { AxiosResponse } from 'axios';
import { IListPatientsResponse, ILoginResponse } from 'interfaces';
import { IAppointmentsResponse, IAppointment } from 'interfaces/appointments.interfaces';
import { IDoctorResponse } from 'interfaces/doctors.interface';
import {
	IPatienDataRegister,
	IPatientUpdate,
} from 'interfaces/patients.interfaces';
import { appRequest, publicRequest } from './config';

type IGetPatiensParams = {
	limit?: number | string;
	page?: number | string;
	sort?: number | string;
	companyId: string;
};

export const login = async (data: { password: string; email: string }) => {
	return publicRequest.post<ILoginResponse>('/auth/login', data);
};

export const refresh = async () => {
	return appRequest.get<ILoginResponse>('/auth/resfresh-token');
};

export const getEventByCompany = async ({
	limit = 15,
	page = 1,
	doctor,
	from,
	includeInactive = false,
	to,
	companyId,
}: {
	from?: string;
	to?: string;
	includeInactive?: boolean;
	limit?: number | string;
	page?: number | string;
	doctor?: string;
	companyId: string;
}): Promise<AxiosResponse<IAppointmentsResponse, any>> => {
	const resp = appRequest.get<IAppointmentsResponse>(
		`/appointments/company/id/${companyId}`,
		{
			params: {
				limit,
				page,
				doctor,
				from,
				to,
				includeInactive,
			},
		}
	);

	return resp;
};

export const registerPatients = (patientsData: IPatienDataRegister) => {
	const resp = appRequest.post('/contacts/add', { ...patientsData });
	return resp;
};

export const getPatiens = async ({
	limit = 15,
	page = 1,
	sort = 'desc',
	companyId,
}: IGetPatiensParams) => {
	const resp = appRequest.get<IListPatientsResponse>(
		`/contacts/list-contact/${companyId}`,
		{
			params: {
				limit,
				page,
				sort,
				kind: 'client',
			},
		}
	);

	return resp;
};

export const removePatient = async (id: string) => {
	const resp = appRequest.delete(`/contacts/delete/${id}`);
	return resp;
};

export const getPatiensByDni = (dni: string, companyId: string) => {
	const resp = appRequest.get(`/contacts/${dni}`, { params: { companyId } });

	return resp;
};

// Generated by https://quicktype.io

export const updatePatient = (id: string, { ...body }: IPatientUpdate) => {
	const resp = appRequest.put(`/contacts/update/${id}`, { ...body });
	return resp;
};



// appointments

export const registerAppointment = async (body: IAppointment) => {

	const resp = appRequest.post('/events/add', { ...body })
	return resp

}

interface queryDoctorsProps {
	companyId: string;
	limit?: string | number,
	page?: string | number
}

export const queryDoctors = ({ companyId, limit = 10, page = 1 }: queryDoctorsProps) => {

	const resp = appRequest.get<IDoctorResponse>(`/doctors/companyId/${companyId}`, {

		params: {
			limit,
			page
		}
	})


	return resp

}

interface RegisterDoctorsProps {
	companyId: string,
	phone: string,
	name: string
}

export const registerDoctor = async ({ companyId, name, phone }: RegisterDoctorsProps) => {
	const resp = appRequest.post(`/doctors/create/${companyId}`, { name, phone })
	return resp
}

export interface updateDoctorProps {
	id: string,
	name: string,
	phone: string
}

export const updateDoctor = async ({ id, name, phone }: updateDoctorProps) => {
	const resp = appRequest.put(`/doctors/update/${id}`, { name, phone })
	return resp
}