// Generated by https://quicktype.io

import { IPatient } from "./patients.interfaces";

export interface AppointmentsResponse {
	data: Data;
}

export interface Data {
	docs: Appointment[];
	totalDocs: number;
	limit: number;
	totalPages: number;
	page: number;
	pagingCounter: number;
	hasPrevPage: boolean;
	hasNextPage: boolean;
	prevPage: null | boolean;
	nextPage: null | boolean;
}

export interface Appointment {
	_id: string;
	id: string;
	title: string;
	description: string;
	dateEvent: string;
	startDateEvent: string;
	endDateEvent: string;
	companyId: string;
	branchOffice: string;
	doctor: string;
	patient: IPatient;
	patientDni: string;
	status: boolean;
	state: string;
	paymentState: string;
	observations: string;
	confirmationMessageSent: boolean;
	createdBy: string;
	createdAt: string;
	updatedAt: string;
}



// Generated by https://quicktype.io

export interface RegisterAppointmentProps {
	title: string;
	description: string;
	observations: string;
	companyId: string;
	doctor: string;
	patient: string;
	patientDni: string;
	dateEvent: string;
	startDateEvent?: string;
	endDateEvent?: string;
}


export interface AddAppointmentProps {
	dateEvent: string, doctor: string, observations: string, patient: string, patientDni: string, title: string, description: string
}