// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface IListPatientsResponse {
	message: string;
	data: Data;
}

export interface Data {
	docs: IPatient[];
	totalDocs: number;
	offset: number;
	limit: number;
	totalPages: number;
	page: number;
	pagingCounter: number;
	hasPrevPage: boolean;
	hasNextPage: boolean;
	prevPage: null;
	nextPage: null;
}

export interface IPatient {
	_id: string;
	name: string;
	lastName: string;
	email: string;
	dni: string;
	city: string;
	phone: string;
	kind: string;
	createBy: string;
	companyId: string;
	companyCode: string;
	companyEmail: string;
	code: string;
	status: boolean;
	createdAt: string;
	updatedAt: string;
}

export interface IPatienDataRegister {
	name: string;
	lastName: string;
	city: string;
	kind: string;
	email: string;
	dni: string;
	phone: string;
	companyEmail: string;
	companyId: string;
	companyCode: string;
}

export interface IPatientForm {
	name: string;
	lastName: string;
	city: string;
	kind: string;
	email: string;
	dni: string;
	phone: string;
}
